source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

target 'UnityFramework' do
  pod 'Firebase/Auth', '10.1.0'
  pod 'Firebase/Core', '10.1.0'
  pod 'Firebase/Database', '10.1.0'
  pod 'Firebase/Firestore', '10.1.0'
  pod 'Firebase/Storage'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
